server:
  port: 80
eureka:
  client:
    register-with-eureka: false #不向eureka注册自己
    service-url:
      defaultZone: http://localhost1:7001/eureka/,http://localhost2:7002/eureka/,http://localhost2:7002/eureka/ #注册地址
#eureka配置