server:
  port: 7002

eureka:
  instance:
    hostname: localhost2 #eureka服务端的实例名称 集群配置时，hostname不能一样
  client:
    register-with-eureka: false #是否向eureka注册中心注册自己
    fetch-registry: false #false表示自己为注册中心
    service-url: #监控页面地址
      #单机：defaultZone: http://localhost:${server.port}/eureka/ #注册地址
      #集群（关联7001,7003）
      defaultZone: http://localhost1:7001/eureka/,http://localhost3:7003/eureka/ #注册地址